rails/config/routes.rb
Rails.application.routes.draw do
  root 'base#index'

  resources :tracks, only: [:index]
  resources :genres, only: [:show]
  namespace :admin do
    root 'admin#index'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    resources :users, only: [:edit, :update]
    resources :tracks, only: [:index, :edit, :update, :destroy] do
      resources :genres, only: [:create, :destroy]
      resources :categories, only: [:create, :destroy]
      collection {post :import}
    end
    resources :genres, only: [:index, :show, :destroy]
    resources :categories, only: [:index, :show, :destroy]

  end
end

rails/app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :tracks
  validates :name, presence: true

  def tweeted_tracks
    tracks.map{|t| t if t.tweeted?}.compact
  end

  def not_tweeted_tracks
    tracks.map{|t| t unless t.tweeted?}.compact
  end
end

rails/app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :logged_in_user

  def index
    @categories = Category.all.order(:name)
  end

  def show
    page = params[:page] || 1
    @category = Category.includes(:tracks).find(params[:id])
    @tracks = @category.tracks.page(page).per(25)
  end

  def create
    if params[:track_id]
      @track = Track.find(params[:track_id])
      @track.add_category(strong_params[:name])
      @category = Category.find_by(name: strong_params[:name])
      if @track.save
        respond_to do |format|
          format.html { redirect_to edit_admin_track_path(@track.sc_id) }
          format.js
        end
      else
        render 'admin/tracks/edit'
      end
    end
  end

  def destroy
    category = Category.find(params[:id])
    if params[:track_id]
      track = Track.find(params[:track_id])
      track.delete_category(params[:id])
      @category_id = params[:id]
      if track.save
        respond_to do |format|
          format.html { redirect_to edit_admin_track_path(track.sc_id) }
          format.js
        end
      else
        render 'admin/tracks/edit'
      end
    else
      category.destroy
      redirect_to admin_categories_path
    end
  end

  private
  def strong_params
    params.require(:category).permit(
      :name
    )
  end
end

rails/app/views/admin/categories/_category.html.erb
<span id="<%= "category-link-#{category.id}" %>">
  <%= link_to category.name, admin_category_path(category.id) %>
  <%=
    link_to "x", admin_track_category_path(track, category), method: :delete,
    data: { confirm: "delete category #{category.name}?" },
    remote: true
  %>
</span>

rails/app/views/admin/categories/create.js.erb
var html = "<%= escape_javascript(render 'admin/categories/category', category: @category, track: @track)%>";
$("#category-links").append($(html));
$("#category_name").val("");

rails/app/views/admin/categories/destroy.js.erb
$("<%= escape_javascript("#category-link-#{@category_id}") %>").remove();

rails/app/views/admin/categories/index.html.erb
<h1>Categories</h1>
<ul>
  <% @categories.each do |category| %>
    <li>
      <%= link_to category.name, admin_category_path(category) %>
    </li>
  <% end %>
</ul>

rails/app/views/admin/categories/show.html.erb
<h1>Category <%= @category.name %></h1>
<h3>Tracks</h3>
<div class="tracks-list">
  <%= render partial: 'admin/tracks/track_card', collection: @tracks, as: "track" %>
</div>
<%= paginate @tracks %>
<div class="editor-group">
  <%= link_to "delete this category", admin_category_path(@category), method: :delete,
    data: { confirm: "delete category #{@category.name}?" }
  %>
</div>