rails/config/routes.rb
Rails.application.routes.draw do
  root 'base#index'

  resources :tracks, only: [:index]
  resources :genres, only: [:show]
  namespace :admin do
    root 'admin#index'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    resources :users, only: [:edit, :update]
    resources :tracks, only: [:index, :edit, :update, :destroy] do
      resources :genres, only: [:create, :destroy]
      resources :categories, only: [:create, :destroy]
      collection {post :import}
    end
    resources :genres, only: [:index, :show, :destroy]
    resources :categories, only: [:index, :show, :destroy]

  end
end

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kawaii Dance Music Daisuki</title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <h1 class="page-header"><%= link_to "Kawaii Dance Music Daisuki Ojisan's Playlist", root_url %></h1>
      <% if logged_in? %>
        <%= link_to "top", admin_root_path %>
        <%= link_to "tracks", admin_tracks_path %>
        <%= link_to "genres", admin_genres_path %>
        <%= link_to "categories", admin_categories_path %>
        <%= link_to "change_password", edit_admin_user_path(current_user) %>
        <%= link_to 'logout', admin_logout_path, method: :delete%>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>