rails/config/routes.rb
Rails.application.routes.draw do
  root 'base#index'

  resources :tracks, only: [:index]
  resources :genres, only: [:show]
  namespace :admin do
    root 'admin#index'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    resources :users, only: [:edit, :update]
    resources :tracks, only: [:index, :edit, :update, :destroy] do
      resources :genres, only: [:create, :destroy]
      resources :categories, only: [:create, :destroy]
      collection {post :import}
    end
    resources :genres, only: [:index, :show, :destroy]
    resources :categories, only: [:index, :show, :destroy]

  end
end

rails/app/models/track.rb
class Track < ApplicationRecord
  has_and_belongs_to_many :genres
  has_and_belongs_to_many :categories
  validates :sc_id, presence: true
  validates :url, presence: true
  validates :artist, presence: true
  validates :title, presence: true
  paginates_per 5

  scope :random, -> (size) {
    self.where(id: self.pluck(:id).shuffle[0..size-1])
        .order_random
  }
  scope :order_random, -> { order(:random_order) }
  scope :sort_by_newest, -> { order(created_at: :desc) }
  scope :undescribed, -> { where(description: [nil, '']) }
  scope :nogenre, -> { includes(:genres).where(genres: {id: nil}) }
  scope :nocategory, -> { includes(:categories).where(categories: {id: nil}) }
  scope :by_genre_id, -> (genre_id) {
    where(id: Genre.find(genre_id).tracks.ids)
  }
  scope :include_genres, -> { includes(:genres) }

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # DBに存在すればnext
      next if find_by(sc_id: row["sc_id"])

      track = new
      # CSVからデータを取得し、設定する
      track.attributes = row.to_hash.slice(*updatable_attributes)
      track.save!
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["sc_id", "url", "artist", "title"]
  end

  def self.tweet_tracks(theme, size)
    tracks = []
    # not_tweetedのtrackを取得する
    if size > theme.not_tweeted_tracks.size
      tracks += theme.not_tweeted_tracks
      size_rest = size - theme.not_tweeted_tracks.size
      tracks += theme.tweeted_tracks.sample(size_rest)
    else
      tracks += theme.not_tweeted_tracks.sample(size)
    end
  end

  def self.pick_theme
    model = [Genre, Category].sample
    # 曲数に応じて選択される確率を変える
    weighted_ids = []
    # 未tweetのtrack数に応じて選択される確率を変える
    model.all.each do |record|
      record.not_tweeted_tracks.size.times { weighted_ids << record.id }
    end
    # 全部tweet済だったら
    if weighted_ids.empty?
      model.all.each do |record|
        # 所属する曲数に応じて選択される確率を変える
        record.tracks.size.times { weighted_ids << record.id }
      end
    end
    id = weighted_ids.sample
    model.find(id)
  end

  def self.tweet_theme(least_tracks_size=3, max_retry=3)
    theme = nil
    retry_count = 0
    # 一定数trackがあるテーマを選ぶ
    while (theme.nil? or theme.tracks.size < least_tracks_size) do
      break if retry_count > max_retry
      theme = pick_theme
      retry_count += 1
    end
    theme
  end

  def add_genre(name)
    Genre.create(name: name) unless Genre.find_by(name: name)
    genre = Genre.find_by(name: name)
    unless self.genres.include?(genre)
      self.genres << genre
    end
  end

  def delete_genre(id)
    genre = Genre.find(id)
    self.genres.delete(genre)
  end

  def add_category(name)
    Category.create(name: name) unless Category.find_by(name: name)
    category = Category.find_by(name: name)
    unless self.categories.include?(category)
      self.categories << category
    end
  end

  def delete_category(id)
    category = Category.find(id)
    self.categories.delete(category)
  end

  def tweeted?
    return true if tweeted_at.present?
    return false
  end

end

rails/app/controllers/admin/tracks_controller.rb
class Admin::TracksController < ApplicationController
  before_action :logged_in_user

  def index
    page = params[:page] || 1
    @tracks = query_base.includes(:genres, :categories)
                        .sort_by_newest.page(page).per(25)
  end

  def edit
    @track = Track.find_by(sc_id: params[:id])
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(strong_params)
      respond_to do |format|
        format.html { redirect_to edit_admin_track_path(@track.sc_id) }
        format.js
      end
    else
      render 'admin/tracks/edit'
    end
  end

  def destroy
    Track.find(params[:id]).destroy
    redirect_to admin_tracks_path
  end

  def import
    Track.import(params[:file])
    redirect_to admin_tracks_path, notice: "tracks import done"
  end

  private
  def strong_params
    params.require(:track).permit(
      :description, :comment
    )
  end

  def query_base
    base = Track
    base = base.undescribed if params[:nodescription]
    base = base.nogenre if params[:nogenre]
    base = base.nocategory if params[:nocategory]
    base
  end
end

rails/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    @page = params[:tracks][:page] || 1
    if params[:tracks][:model]
      if params[:tracks][:model] == 'genre'
        genre_id = valid_id(params[:tracks][:model_id])
        @tracks = Track.by_genre_id(genre_id)
                      .include_genres
                      .order_random
                      .page(@page)
      end
    else
      @tracks = Track.random(30).include_genres.page(@page)
    end

    @total_pages = @tracks.total_pages

    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
  end

  private
  def valid_id(text)
    return '' unless text.match(/\A[0-9]*\z/)
    text
  end
end

rails/app/views/admin/tracks/_track_card.html.erb
<div class="track-card">
  <h4>
    <%= link_to "#{track.artist} - #{track.title}", edit_admin_track_path(track.sc_id) %>
  </h4>
  <div class="track-info">
    <p>
      genres:
      <% track.genres.each do |genre| %>
        <%= link_to genre.name, admin_genre_path(genre) %>
      <% end %>
    </p>
    <p>
      cateogries:
      <% track.categories.each do |category| %>
        <%= link_to category.name, admin_category_path(category) %>
      <% end %>
    </p>
    <p>
      description: <%= track.description %>
    </p>
    <p>
      comment: <%= track.comment %>
    </p>
  </div>
</div>

rails/app/views/admin/tracks/edit.html.erb
<h1>Track Edit</h1>
<h3><%= "#{@track.artist} - #{@track.title}" %></h3>
<%= render 'shared/sc_embed', track: @track %>

<div class="editor-group">
  <h4>Genres</h4>
  <div id="genre-links">
    <% if @track.genres.present? %>
      <%=
        render partial: 'admin/genres/genre',
        collection: @track.genres, as: :genre,
        locals: {track: @track}
      %>
    <% end %>
  </div>
  <%= form_with model: Genre.new, url: admin_track_genres_path(@track) do |f| %>
    <%= f.text_field :name %>
    <%= f.submit "add genre"%>
  <% end %>
</div>

<div class="editor-group">
  <h4>Categories</h4>
  <div id="category-links">
    <% if @track.categories.present? %>
      <%=
        render partial: 'admin/categories/category',
        collection: @track.categories, as: :category,
        locals: {track: @track}
      %>
    <% end %>
  </div>
  <%= form_with model: Category.new, url: admin_track_categories_path(@track) do |f| %>
    <%= f.text_field :name %>
    <%= f.submit "add category"%>
  <% end %>
</div>

<div class="editor-group">
  <h4>Description</h4>
  <%= form_with model: @track, url: admin_track_path(@track), method: :patch do |f| %>
    <%= f.text_field :description, size: 100 %>
    <%= f.submit "update description"%>
  <% end %>
</div>

<div class="editor-group">
  <h4>Comment</h4>
  <%= form_with model: @track, url: admin_track_path(@track), method: :patch do |f| %>
    <%= f.text_field :comment, size: 100 %>
    <%= f.submit "update comment"%>
  <% end %>
</div>

<div class="editor-group">
  <%= link_to "delete this track", admin_track_path(@track), method: :delete,
    data: { confirm: "delete this track?" }
  %>
</div>

rails/app/views/admin/tracks/index.html.erb
<br />
<%= link_to "all", admin_tracks_path %>
<%= link_to "nodescription", admin_tracks_path(nodescription: "true") %>
<%= link_to "nogenre", admin_tracks_path(nogenre: "true") %>
<%= link_to "nocategory", admin_tracks_path(nocategory: "true") %>
<h1>Tracks</h1>
<%= form_tag import_admin_tracks_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "import" %>
<% end %>
<div class="tracks-list">
  <%= render partial: 'admin/tracks/track_card', collection: @tracks, as: "track" %>
</div>
<%= paginate @tracks %>

rails/app/views/admin/tracks/update.js.erb
$("#tracks_description").val("<%= escape_javascript(@track.description) %>");
$("#tracks_comment").val("<%= escape_javascript(@track.comment) %>");