rails/config/routes.rb
Rails.application.routes.draw do
  root 'base#index'

  resources :tracks, only: [:index]
  resources :genres, only: [:show]
  namespace :admin do
    root 'admin#index'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    resources :users, only: [:edit, :update]
    resources :tracks, only: [:index, :edit, :update, :destroy] do
      resources :genres, only: [:create, :destroy]
      resources :categories, only: [:create, :destroy]
      collection {post :import}
    end
    resources :genres, only: [:index, :show, :destroy]
    resources :categories, only: [:index, :show, :destroy]

  end
end

rails/app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :tracks
  validates :name, presence: true

  def tweeted_tracks
    tracks.map{|t| t if t.tweeted?}.compact
  end

  def not_tweeted_tracks
    tracks.map{|t| t unless t.tweeted?}.compact
  end
end

rails/app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :logged_in_user

  def index
    @genres = Genre.all.order(:name)
  end

  def show
    page = params[:page] || 1
    @genre = Genre.includes(:tracks).find(params[:id])
    @tracks = @genre.tracks.page(page).per(25)
  end

  def create
    if params[:track_id]
      @track = Track.find(params[:track_id])
      @track.add_genre(strong_params[:name])
      @genre = Genre.find_by(name: strong_params[:name])
      if @track.save
        respond_to do |format|
          format.html { redirect_to edit_admin_track_path(@track.sc_id) }
          format.js
        end
      else
        render 'admin/tracks/edit'
      end
    end
  end

  def destroy
    genre = Genre.find(params[:id])
    if params[:track_id]
      track = Track.find(params[:track_id])
      track.delete_genre(params[:id])
      @genre_id = params[:id]
      if track.save
        respond_to do |format|
          format.html { redirect_to edit_admin_track_path(track.sc_id) }
          format.js
        end
      else
        render 'admin/tracks/edit'
      end
    else
      genre.destroy
      redirect_to admin_genres_path
    end
  end

  private
  def strong_params
    params.require(:genre).permit(
      :name
    )
  end
end

rails/app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def show
    @genre = Genre.find(params[:id])
  end
end

rails/app/views/admin/genres/_genre.html.erb
<span id="<%= "genre-link-#{genre.id}" %>">
  <%= link_to genre.name, admin_genre_path(genre.id) %>
  <%=
    link_to "x", admin_track_genre_path(track, genre), method: :delete,
    data: { confirm: "delete genre #{genre.name}?" },
    remote: true
  %>
</span>

rails/app/views/admin/genres/create.js.erb
var html = "<%= escape_javascript(render 'admin/genres/genre', genre: @genre, track: @track)%>";
$("#genre-links").append($(html));
$("#genre_name").val("");

rails/app/views/admin/genres/destroy.js.erb
$("<%= escape_javascript("#genre-link-#{@genre_id}") %>").remove();

rails/app/views/admin/genres/index.html.erb
<h1>Genres</h1>
<ul>
  <% @genres.each do |genre| %>
    <li>
      <%= link_to genre.name, admin_genre_path(genre) %>
    </li>
  <% end %>
</ul>

rails/app/views/admin/genres/show.html.erb
<h1>Genre <%= @genre.name %></h1>
<h3>Tracks</h3>
<div class="tracks-list">
  <%= render partial: 'admin/tracks/track_card', collection: @tracks, as: "track" %>
</div>
<%= paginate @tracks %>
<div class="editor-group">
  <%= link_to "delete this genre", admin_genre_path(@genre), method: :delete,
    data: { confirm: "delete genre #{@genre.name}?" }
  %>
</div>